version: '3.9'

services:
  service:
    container_name: jwt_auth_service
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    depends_on:
      - mongodb
    env_file:
      .env

  mongodb:
    image: mongo
    container_name: jwt_auth_service_mongodb
    restart: always
    ports:
      - ${MONGODB_PORT}:${MONGODB_PORT}
    volumes:
      - mongodb-data:/data/db
    env_file:
      - .env

volumes:
  mongodb-data: